wsdp/WebApp/Controllers/BaseController.cs
using System.Globalization;
using System.Threading;
using System.Web;
using System.Web.Mvc;

namespace WebApp.Controllers
{
    public class BaseController : Controller
    {
        public ActionResult Change(string language, string url)
        {
            if (language != null)
            {
                Thread.CurrentThread.CurrentCulture = CultureInfo.CreateSpecificCulture(language);
                Thread.CurrentThread.CurrentUICulture = new CultureInfo(language);
            }
            HttpCookie cookie = new HttpCookie("Language");
            cookie.Value = language;
            Response.Cookies.Add(cookie);

            return Redirect(url);
        }

    }
}

wsdp/WebApp/Controllers/GoodController.cs
using BAL.Interface;
using Model.DTO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Newtonsoft.Json;
using PagedList;

namespace WebApp.Controllers
{
	public class GoodController : BaseController
	{
		private IGoodManager goodmanager = null;
		private IElasticManager elasticmanager = null;
		private IPropertyManager propertymanager = null;
		private ICategoryManager categoryManager = null;
		private IWebShopManager webShopManager = null;
		private IFollowPriceManager followPriceManager;
		private IUserManager userManager;
		private ICommentManager commentManager;

		public GoodController(IGoodManager goodmanager, IElasticManager elasticmanager, IPropertyManager propertymanager, ICategoryManager categoryManager, IWebShopManager webShopManager, IFollowPriceManager followPriceManager,IUserManager userManager, ICommentManager commentManager)
		{
			this.userManager = userManager;
			this.webShopManager = webShopManager;
			this.categoryManager = categoryManager;
			this.goodmanager = goodmanager;
			this.elasticmanager = elasticmanager;
			this.propertymanager = propertymanager;
			this.followPriceManager = followPriceManager;
			this.commentManager = commentManager;
		}
		// GET: Good
		public ActionResult ConcreteGood(int id)
		{
			var comments = commentManager.GetAllCommentsByGoodId(id).ToList();
			GoodViewModelDTO mainmodel = new GoodViewModelDTO();
			GoodDTO good = goodmanager.GetAndCheckUser(id,Convert.ToInt32(User.Identity.GetUserId()));

			mainmodel.Good = good;

            ListCompareGoodDTO compgoods = Session["ComparingGoods"] as ListCompareGoodDTO;
            try
            {
                mainmodel.IsComparing = compgoods.CompareGoods[good.Category_Id].Contains(id);
            }
            catch
            {
                mainmodel.IsComparing = false;
            }

			List<GoodDTO> alloffers = new List<GoodDTO>();
			List<GoodDTO> similaroffers = new List<GoodDTO>();

			Dictionary<string, string> properties = new Dictionary<string, string>();

			foreach (var item in good.PropertyValues.DictStringProperties)
			{
				string propertyname = propertymanager.Get(item.Key).Name;
				properties.Add(propertyname, item.Value);
			}
			//similaroffers = elasticmanager.GetSimilar(good.Name.Split(' ')[1]).ToList();
			similaroffers = elasticmanager.GetSimilar(good.Name).ToList();
			alloffers = elasticmanager.GetByName(good.Name).ToList();

			foreach (var simgood in similaroffers)
			{
				simgood.Category = categoryManager.Get(simgood.Category_Id);
				simgood.WebShop = webShopManager.GetById(simgood.WebShop_Id);
			}

			decimal minprice = (decimal)(similaroffers.Select(c => c.Price).Min() ?? good.Price);
			decimal maxprice = (decimal)(similaroffers.Select(c => c.Price).Max() ?? good.Price);

			mainmodel.AllOffers = alloffers;
			mainmodel.SimilarOffers = similaroffers;
			mainmodel.MinPrice = minprice;
			mainmodel.MaxPrice = maxprice;
			mainmodel.Properties = properties;
			if(User.Identity.IsAuthenticated)
			{
				mainmodel.UserId = Convert.ToInt32(User.Identity.GetUserId());
			}
			else
			{
				mainmodel.UserId = null;
			}
			
			mainmodel.Comments = commentManager.CheckCommentsDependency(Convert.ToInt32(User.Identity.GetUserId()), id).ToList();

            foreach (var comment in mainmodel.Comments)
            {
                comment.User = userManager.GetById(comment.UserId);
            }

			return View(mainmodel);
		}
		public ActionResult GetCategoryGood(int c_Id,int? page)
		{
			//var goodListCat=elasticmanager.GetByCategoryId(c_Id);
			var goodListCat = goodmanager.GetAll().Where(i => i.Category_Id == c_Id).ToList();
			
			
			foreach (var item in goodListCat)
			{
				item.Category = categoryManager.Get(item.Category_Id);

				item.WebShop = webShopManager.GetById(item.WebShop_Id);
			}
			var categoryName = goodListCat.First().Category.Name;
			if (!goodListCat.Any())
			{
				return View("../Error/CategoryNotFound");
			}
			else
			{
				ViewBag.cat_id = c_Id;
				int pageSize = 10;
				int pageNumber = (page ?? 1);
				var modelView = new GetCategoryDTO() {
					CategoryName = categoryName,
					GoodListCategory= goodListCat.ToPagedList(pageNumber, pageSize)
				};
				return View(modelView);
			}
		}

		public ActionResult EmptyList()
		{
			return View();
		}

		/// <summary>
		/// Post method for inserting follower to db.
		/// </summary>
		/// <param name="good_Id"></param>
		/// <param name="user_Id"></param>
		/// <param name="price"></param>
        [HttpPost]
		public void FollowGoodPrice(string good_Id, string user_Id,string price)
		    {
			if(Request.IsAuthenticated)
			{

				var model = new PriceFollowerDTO()
				{
					Good_Id = Convert.ToInt32(good_Id),
					User_Id = Convert.ToInt32(user_Id),
					Price = Convert.ToDecimal(price)
                };
                followPriceManager.Insert(model);
            }
            else
            {
                RedirectToAction("SignUp", "Account");
            }
			
			
		}
		/// <summary>
		/// Method Post for unfollowing good and deleting from db.
		/// </summary>
		/// <param name="good_Id"></param>
		/// <param name="user_Id"></param>
		[HttpPost]
		public void DeleteGoodFollow(string good_Id, string user_Id)
		{
			var del_id = followPriceManager.GetAll().
				Where(i => i.Good_Id == Convert.ToInt32(good_Id) && i.User_Id == Convert.ToInt32(user_Id)).
				Select(i => i.id).FirstOrDefault();
			followPriceManager.Delete(del_id);

		}

		public ActionResult GetGoodsByName(string name)
		{
			if (name == null) return HttpNotFound();
		  

			var goodList = elasticmanager.GetExact(name);
			if (goodList.Count == 0) return RedirectToAction("EmptyList");
			foreach (var item in goodList)
			{
				item.WebShop = webShopManager.GetById(item.WebShop_Id);
				item.Category = categoryManager.Get(item.Category_Id);
                if (name == "Наклофен ДУО 75 мг №20 капсулы") item.Id = 17;
                else item.Id = 2;
			}
			return View(goodList);
		}

        [HttpPost]
        public void SetCompareGood(int id)
        {
            GoodDTO good = goodmanager.Get(id);
            int categoryId = good.Category_Id;

            ListCompareGoodDTO compgoods = Session["ComparingGoods"] as ListCompareGoodDTO;

            if (compgoods == null)
            {
                compgoods = new ListCompareGoodDTO();

                if (!compgoods.CompareGoods.ContainsKey(categoryId))
                {
                    compgoods.CompareGoods.Add(categoryId, new List<int>());
                }
                compgoods.CompareGoods[categoryId].Add(id);
                Session["ComparingGoods"] = compgoods;
                return;
            }
            else
            {
                if (compgoods.CompareGoods[categoryId].Find(c => c == id) != -1)
                {
                    compgoods.CompareGoods[categoryId].Add(id);
                    Session["ComparingGoods"] = compgoods;
                    return; 
                }
            }
        }

        [HttpPost]
        public void UnsetCompareGood(int id)
        {
            GoodDTO good = goodmanager.Get(id);
            int categoryId = good.Category_Id;

            ListCompareGoodDTO compgoods = Session["ComparingGoods"] as ListCompareGoodDTO;

            if (compgoods == null)
            {
                return;
            }
            else
            {
                compgoods.CompareGoods[categoryId].Remove(id);
                Session["ComparingGoods"] = compgoods;
                return;
            }
        }

        [HttpGet]
        public ActionResult ComparingCategories()
        {
            ComparingCategoriesDTO model = new ComparingCategoriesDTO();
            ListCompareGoodDTO goods = Session["ComparingGoods"] as ListCompareGoodDTO;
            model.CategoriesGoods = new Dictionary<CategoryDTO, List<GoodDTO>>();
            foreach (var key in goods.CompareGoods.Keys)
            {
                CategoryDTO category = categoryManager.Get(key);
                model.CategoriesGoods.Add(category, new List<GoodDTO>());
                foreach (var good_id in goods.CompareGoods[key])
                {
                    GoodDTO good = goodmanager.Get(good_id);
                    model.CategoriesGoods[category].Add(good);
                }
            }
            return View(model);
        }

        public ActionResult CompareGoods(int id)
        {
            List<string> properties = new List<string>();

            ListCompareGoodDTO goodsFromSession = Session["ComparingGoods"] as ListCompareGoodDTO;

            List<int> goodsIds = goodsFromSession.CompareGoods[id].ToList();

            List<GoodDTO> goods = new List<GoodDTO>();

            foreach (var good_id in goodsIds)
            {
                goods.Add(goodmanager.Get(good_id));
            }


            foreach (var item in goods.First().PropertyValues.DictStringProperties)
            {
                string propertyname = propertymanager.Get(item.Key).Name;
                properties.Add(propertyname);
            }


            CompareGoodsDTO model = new CompareGoodsDTO()
            {
                Goods = goods,
                Properties = properties
            };

            return View(model);
        }

        //[Authorize(Roles = "Administrator, User")]
		[HttpPost]
		public int AddComment(string text, int goodId) {
			var comment = new CommentDTO() {
				GoodId = goodId,
				UserId = Convert.ToInt32(User.Identity.GetUserId()),
				Description = text,
				Date = DateTime.Now
			};
            return commentManager.Insert(comment);
		}

		[Authorize(Roles = "Administrator, User")]
		[HttpPost]
		public bool DeleteComment(int commentId) {
			var comment = commentManager.GetById(commentId);

			if (Convert.ToInt32(User.Identity.GetUserId()) == comment.UserId) {

wsdp/WebApp/Controllers/WebShopController.cs
using BAL.Interface;
using Model.DTO;
using System;
using System.Collections.Generic;
using System.IO;
using System.Web;
using System.Web.Mvc;

namespace WebApp.Controllers
{
    [Authorize]
    public class WebShopController : BaseController
    {
        /// <summary>
        /// The variable gives the acces to DB for WebShopSTO
        /// </summary>
        private IWebShopManager WebShopManager { get; }

        public WebShopController(IWebShopManager webShopManager)
        {
            WebShopManager = webShopManager;
        }

        /// <summary>
        /// To show a View with all WebShops in the DB
        /// </summary>
        public ActionResult Index()
        {
            IEnumerable<WebShopDTO> webShopsList = WebShopManager.GetAll();
            return View(webShopsList);
        }

        /// <summary>
        /// To show create view for WebShopDTO
        /// </summary>
        [Authorize(Roles = "Administrator")]
        public ActionResult Create()
        {
            return View(new WebShopDTO());
        }

        /// <summary>
        /// To create new WebShop and insert into DB and redirest to all WebShopDTOs
        /// </summary>
        [Authorize(Roles = "Administrator")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(WebShopDTO webShop, HttpPostedFileBase upload)
        {
            if (!ModelState.IsValid) return View(webShop);
            if (upload != null)
            {
                webShop.LogoPath = CreateImgName();
                var path = Path.Combine("~", GetLogoDirectory(), webShop.LogoPath);
                upload.SaveAs(Server.MapPath(path));
            }
            WebShopManager.Insert(webShop);
            return RedirectToAction("Index");
        }

        /// <summary>
        /// To show delete view
        /// </summary>
        [Authorize(Roles = "Administrator")]
        public ActionResult Delete(int? id)
        {
            if (id == null) return HttpNotFound();
            WebShopDTO webShop = WebShopManager.GetById((int)id);
            if (webShop != null)
                return PartialView(webShop);
            return HttpNotFound();
        }

        /// <summary>
        /// To delete WebShop in the DB and redirect to all WebShopDTOs
        /// </summary>
        [Authorize(Roles = "Administrator")]
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            WebShopDTO wShop = WebShopManager.GetById(id);
            WebShopManager.Delete(wShop);
            return RedirectToAction("Index");
        }

        /// <summary>
        /// To show edit view for WebShopDTO
        /// </summary>
        [Authorize(Roles = "Administrator")]
        public ActionResult Edit(short? id)
        {
            if (id == null) return HttpNotFound();

            WebShopDTO webShop = WebShopManager.GetById((int)id);
            if (webShop == null) return HttpNotFound();

            return View(webShop);
        }

        /// <summary>
        /// To edit WebShop in the DB and redirect to all WebShopDTOs
        /// </summary>
        [Authorize(Roles = "Administrator")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(WebShopDTO webShop, HttpPostedFileBase upload)
        {
            if (!ModelState.IsValid) return View(webShop);
            if (upload != null)
            {
                webShop.LogoPath = CreateImgName();
                var path = Path.Combine("~", GetLogoDirectory(), webShop.LogoPath);
                upload.SaveAs(Server.MapPath(path));
            }
            WebShopManager.Update(webShop);
            return RedirectToAction("Index");
        }

        /// <summary>
        /// To create an unique image's name
        /// </summary>
        [Authorize(Roles = "Administrator")]
        private string CreateImgName()
        {
            return String.Format("IMG_{0}_{1}.jpg",
                DateTime.Now.ToString("yyyyMMddHHmmssfff"),
                Guid.NewGuid());
        }

        private string GetLogoDirectory()
        {
            var path = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "Content", "WebShopLogos");
            var info = new DirectoryInfo(path);
            if(!info.Exists)
            Directory.CreateDirectory(path);
            return Path.Combine("Content", "WebShopLogos");
        }
    }
}

wsdp/WebApp/Views/Shared/_ComparePartial.cshtml
@{
    var model = Session["ComparingGoods"] as Model.DTO.ListCompareGoodDTO;

    var count = 0;

    
    if (model!=null && model.CompareGoods!=null)
    {
        foreach (var item in model.CompareGoods)
        {
            count += item.Value.Count;
        }
    }
}

@if (count!=0)
{
    <li><a href="@Url.Action("ComparingCategories","Good")"><span class="glyphicon glyphicon-stats"></span> <span class="badge">@count</span></a></li>
}

wsdp/WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - WSDP Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="stylesheet" type="text/css" href="~/Content/sidebar-style.css">
    <link rel="stylesheet" href="~/Content/themes/base/all.css" type="text/css" />
    <style>
        .navbar-default {
            background: #02578e !important;
        }

        footer {
            position: fixed;
            width: 100%;
            bottom: 0;
            z-index: 1000;
            height: 75px;
            background: white;
        }

        footer hr {
            margin-top: 0
        }

        footer a {
            color: #3498db;
            text-decoration: none;
        }

        footer a:hover,
        footer a:focus,
        footer a:active,
        footer a:visited {
            color: #02578e;
        }

        .dataTables_paginate .paginate_button > a {
            background: #3498db;
        }

        .dataTables_paginate .paginate_button a:hover,
        .dataTables_paginate .active > a,
        .dataTables_paginate .active > a:hover {
            background: #02578e;
        }

    </style>
</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink(@Resources.Resource.HealthyLine, "Index", "Home", new { area = "" }, new { @class = "navbar-brand custom-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink(Resources.Resource.Home, "Index", "Home")</li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"> @Resources.Resource.AdminSettings <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink(@Resources.Resource.EditCategories, "EditCategories", "Admin")</li>
                            <li class="divider"></li>
                            <li>@Html.ActionLink(@Resources.Resource.EditUsers, "EditUsers", "Admin")</li>
                            <li class="divider"></li>
                            <li>@Html.ActionLink(Resources.Resource.AddPharmacy, "Create", "WebShop")</li>
                            <li>@Html.ActionLink(Resources.Resource.WebPharmacies, "Index", "WebShop")</li>
                            <li class="divider"></li>
                            <li>@Html.ActionLink(@Resources.Resource.AddNewParserTask, "Settings", "UniversalParser")</li>
                            <li>@Html.ActionLink(@Resources.Resource.ViewAllTasks, "Index", "UniversalParser")</li>
                            <li>@Html.ActionLink(@Resources.Resource.ExecutingTasks, "ExecutingTasks", "UniversalParser")</li>
                            <li class="divider"></li>
                            <li>@Html.ActionLink(@Resources.Resource.CheckExistGoods, "CheckExistGoods", "Admin")</li>
                        </ul>
                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    @Html.Partial("_LoginPartial")
                    @Html.Partial("_ComparePartial")
                </ul>
            </div>
        </div>
    </div>

    <hr />
    <br />
    <div class="container body-content">
        <div class="row">
            <div class="col-sm-12">
                @RenderBody()
            </div>
        </div>
    </div>
    <footer>
        <hr />
        <ul class="list-inline text-center">
            <li>@Html.ActionLink("UA", "Change", "Base", new { language = "uk-UA", url = Request.Url.AbsoluteUri }, null)</li>
            <li>@Html.ActionLink("RU", "Change", "Base", new { language = "ru-RU", url = Request.Url.AbsoluteUri }, null)</li>
            <li>@Html.ActionLink("EN", "Change", "Base", new { language = "en", url = Request.Url.AbsoluteUri }, null)</li>
        </ul>
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/jquery-ui")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/EditProperties")
    @Scripts.Render("~/bundles/WebShop")
    @Scripts.Render("~/bundles/EditUsers")
    @Scripts.Render("~/Content/editcategories")
    @Styles.Render("~/content/EditUsers_css")
    @Scripts.Render("~/bundles/PriceStat")
    @Scripts.Render("~/bundles/executing_tasks")
    @Scripts.Render("~/bundles/GoodAutocomplete")
    @Scripts.Render("~/bundles/ExecutingInfo")
    @Scripts.Render("~/bundles/jquery-timeago")
    @RenderSection("scripts", required: false)

</body>
</html>